### ISSUE TITLE
The screenshots in the readme do not show up in firefox

### ISSUE THREAD

**Issue by bradjc** [lab11/summon#13]
The images have a weird file type.

**Comment by tzachari** [comment]
Fixed

**Comment by bradjc** [comment]
Bringing this back!

**Comment by ppannuto** [comment]
Also broken on mobile, somewhat ironically

**Comment by tzachari** [comment]
I didn't see the issue on mobile, but assuming it was the same as Firefox's, it should be fixed.

**Comment by ppannuto** [comment]
Confirm. Fixed.
