### ISSUE TITLE
Kindle Fire support

### ISSUE THREAD

**Issue by vielmetti** [lab11/summon#19]
I have a Kindle Fire that I have successfully run Cordova apps on. App distribution for that device is either via the Amazon store (not the Google Play store) or by downloading an APK.

If an APK bundle is available somehow I'd love to try it out.

**Comment by tzachari** [comment]
I've shared the Android APK with you via Google Drive. I haven't had a chance to test on a Kindle Fire, so I'd been interested to hear if Summon works on Amazon's OS. However, having taken just a quick glance at the Fire's tech specs, it seems like it may not have proper Bluetooth Low Energy support.

**Comment by vielmetti** [comment]
Thanks, I'll give this a try and report back.

**Comment by vielmetti** [comment]
The good news is that the APK loads just fine. The bad news is that on the Kindle Fire it doesn't see the BLEES tag that I have. I've confirmed that the tag is visible via the Beaglebone gateway. 

Summon loads properly but instead of seeing the tag it simply has a never-ending spinning circle. The sidebar menus do work.

@tzachari - what was the tech spec document that convinced you that the Fire was lacking proper BLE support? 

Thanks for giving this a try! On to plan B.

**Comment by tzachari** [comment]
I guess it was more of a hunch, really. 

I know FireOS branched off from Android before there was extensive software support for BLE GATT. 

And, I was looking at [specs on official product sites](http://www.amazon.com/dp/B00TSUGXKE/ref=fs_ods_fs_tab_fd#tech), which all list "Bluetooth with support for A2DP compatible stereo headphones, speakers, microphone, and LE accessories support"—an oddly specific set of features that would have been inclusively assumed by simply stating support for Bluetooth ≥ 4.0. 
Android phone tech specs used to have similar descriptions before they had proper software support. 

The [Bluetooth support page for 4th gen Fire tablets](http://www.amazon.com/gp/help/customer/display.html?nodeId=201540210) explicitly notes lack of BLE support. The [5th gen page](http://www.amazon.com/gp/help/customer/display.html?nodeId=201540210) doesn't mention LE at all. The new tablets likely have BLE radios, but they're probably still using legacy software, which would only access LE devices that use classic Bluetooth profiles (like A2DP). 

In any case, thank you for trying it out!

I did find out that Amazon has a service for testing APK compatibility with their platforms. Summon seems to run on all of their platforms including their TV products. And while there was nothing showing Bluetooth devices working with it, it does look like it still works with mDNS.

![image](https://cloud.githubusercontent.com/assets/2251502/12829864/4df3e134-cb5a-11e5-8e71-fe2250cfab16.png)
