### ISSUE TITLE
Network status plugin

### ISSUE THREAD

**Issue by adkinsjd** [lab11/summon#21]
Can you add the plugin to support checking network status? It seems like something necessary for summon to provide.

https://github.com/apache/cordova-plugin-network-information

**Comment by tzachari** [comment]
The plugin is already [included](https://github.com/lab11/summon/blob/55e783329498b76d1a6a46039f3bf71e9439df3f/mobile-app/config.xml#L46).
I've verified that it works properly with the current build on the Play Store.
Are you running into issues while trying to use the plugin?
