### ISSUE TITLE
Caching eddystone URL for devices

### ISSUE THREAD

**Issue by bradjc** [lab11/summon#23]
Does summon keep a map of {device id: eddystone URL} if caching is turned on? This way, once you've seen a device once, any device that alternates eddystone with other advertisements could be put in the top list when any packet is seen, rather than having to wait for the eddystone packet on each use of the summon app.

**Comment by tzachari** [comment]
There is a map, but it's only referenced when the phone is offline or when network failures occur. Your proposed feature should be relatively trivial to implement. I'll push an update to the Play Store later today.

**Comment by tzachari** [comment]
https://github.com/lab11/summon/commit/30c5d598931a8ce25d4ea00f3030ef71c2fe3684
