### ISSUE TITLE
Handle devices that change their advertisements

### ISSUE THREAD

**Issue by bradjc** [lab11/summon#3]
Devices like BLEES alternate between eddystone and data advertisements, and it seems summon groups by ID based on the first advertisement, and doesn't check for subsequent advertisements.

**Comment by brghena** [comment]
Seconded. This makes summon look really unresponsive. How hard would this
be to fix?

**Comment by tzachari** [comment]
New update pushed to the play store handles changing advertisements.

**Comment by bradjc** [comment]
So this appears to use the most recent advertisement, which is not what we need. If the peripheral ever sends an eddystone adv, summon should use that, and ignore future advertisements.

Now BLEES devices show up on the list, then disapear, then come back, as different advertisements come in.

**Comment by tzachari** [comment]
Updated and verified with Powerblade. If a BLE device is detected, it will sit in the "Other Devices" list until it sees a Summon-compatible ad. Depending on how often advertisements are changing, it may take a while for this to happen. I will experiment with increasing refresh rate for quicker detection.
